[build-system]
requires = ["setuptools", "wheel", "setuptools_scm>8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/compressed_tensors/version.py"

[tool.black]
line-length = 88
target-version = ['py36']
