name: generate metadata info file for the run
description: 'generate metadata file'
inputs:
  reportportal_host:
    description: "reportportal hostname"
    required: true
  project:
    description: "reportportal project"
    required: true
  gha_url:
    description: "GHA job url"
    required: true
  wf_category:
    description: "workflow category; will be used in the droute attributes"
    required: true
  gitref:
    description: "gitref for checked out product code; will be used in the droute attributes"
    required: true
  run_name:
    description: "run name; if empty, will use project as default"
outputs:
  metadata_filepath:
    description: "path of the metadata file"
    value: ${{ steps.metadata.outputs.metadata_filepath }}
runs:
  using: composite
  steps:

    - name: generate metadata file
      id: metadata
      run: |

        # wheel is downloaded already
        WHEEL=`find . -type f -name compressed*.whl -exec basename {} \;`
        RUN_NAME=${{ inputs.run_name }}
        if [ -z "${{ inputs.run_name }}" ]; then
          RUN_NAME=${{ inputs.project }}
        fi

        jq --raw-output -n "{
          \"hostname\": \"${REPORTPORTAL_HOST}\",
          \"project": \"${{ inputs.project }}\",
          \"name\": \"${RUN_NAME}\",
          \"description\": \"GitHub run: ${{ inputs.gha_url }}\",
          \"attributes\": {
            \"wheel\": \"${WHEEL}\"
            \"gitref\": \"${{ inputs.gitref }}\",
            \"workflow category\": \"${{ inputs.wf_category }}\"
            }
          }" > metadata.json
        cat metadata.json
        METADATA_FILEPATH=`realpath metadata.json`
        echo "metadata_filepath=${METADATA_FILEPATH}" >> $GITHUB_OUTPUT
      env:
        REPORTPORTAL_HOST: ${{ inputs.reportportal_host }}
      shell: bash
