name: Build nightly wheel

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-wheel-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python }}
      - name: Set Env
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Build PyPi Wheel
        id: build-wheel
        uses: neuralmagic/nm-actions/actions/pypi_build@main
        with:
          dev: false
          release: false

