name: build
on:
  # makes workflow reusable
  workflow_call:
    inputs:
      wf_category:
        description: "categories: NIGHTLY, RELEASE"
        type: string
        default: NIGHTLY
      build_label:
        description: "requested runner label (specifies instance)"
        type: string
        required: true
      timeout:
        description: "time limit for run in minutes "
        type: string
        default: 20
      gitref:
        description: "git commit hash or branch name"
        type: string
        default: main
    outputs:
      whl:
        description: 'basename for generated whl'
        value: ${{ jobs.BUILD.outputs.whl }}

  # makes workflow manually callable
  workflow_dispatch:
    inputs:
      wf_category:
        description: "categories: NIGHTLY, RELEASE"
        type: string
        default: NIGHTLY
      build_label:
        description: "requested runner label (specifies instance)"
        type: string
        required: true
      timeout:
        description: "time limit for run in minutes "
        type: string
        default: 20
      gitref:
        description: "git commit hash or branch name"
        type: string
        default: main

jobs:

    BUILD:

        runs-on: ${{ inputs.build_label }}
        timeout-minutes: ${{ fromJson(inputs.timeout) }}
        permissions:
            contents: 'read'
            id-token: 'write'

        outputs:
            run_id: ${{ github.run_id }}
            whl: ${{ steps.build.outputs.whlname }}
            tarfile: ${{ steps.build.outputs.tarname }}

        steps:

            - name: set python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            - name: checkout code
              id: checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true
                  ref: ${{ inputs.gitref }}

            - name: build
              id: build
              uses: neuralmagic/nm-actions/actions/build-ml-whl@fix-whl-checks
              with:
                  dev: false
                  release: ${{ inputs.wf_category == 'RELEASE' }}
