name: Quality Checks
on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  quality-check:
    runs-on: ubuntu-24.04
    steps:
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            fetch-tags: true
        - name: Set Env
          run: |
            pip3 install --upgrade pip && pip3 install --upgrade setuptools
        - name: "⚙️ Install dependencies"
          run: pip3 install .[dev]
        - name: "🧹 Running quality checks"
          run: make quality