name: report test results to reportportal
run-name: ${{ github.actor }} report results for run ${{ inputs.run_id }}
on:

    workflow_call:
        inputs:
            label:
                description: "requested runner label (specifies instance)"
                type: string
                required: true
            timeout:
                description: "time limit for run in minutes "
                type: string
                required: true
            run_id:
                description: "run_id of 'build.yml' run that generated the assets"
                type: string
                required: true
            wf_category:
                description: "categories: NIGHTLY, RELEASE"
                type: string
                default: NIGHTLY
            gitref:
                description: "git commit hash or branch name"
                type: string
                default: main

    workflow_dispatch:
        inputs:
            label:
                description: "requested runner label (specifies instance)"
                type: string
                required: true
            timeout:
                description: "time limit for run in minutes "
                type: string
                required: true
            run_id:
                description: "run_id of 'build.yml' run that generated the assets"
                type: string
                required: true
            wf_category:
                description: "categories: NIGHTLY, RELEASE"
                type: string
                default: NIGHTLY
            gitref:
                description: "git commit hash or branch name"
                type: string
                default: main

jobs:

    REPORT:
        runs-on: ${{ inputs.label }}
        timeout-minutes: ${{ fromJson(inputs.timeout) }}

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:

            - name: checkout code
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.gitref }}

            - name: install automation components
              uses: neuralmagic/nm-actions/actions/install-automation-components@v1.0.0

            - name: 'Authenticate to Google Cloud'
              id: auth-gcp
              uses: google-github-actions/auth@v2.1.3
              with:
                  project_id: ${{ secrets.GCP_PROJECT }}
                  workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.GCP_GHA_SA }}

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                  version: '>= 473.0.0'

            - name: download assets
              uses: neuralmagic/nm-actions/actions/gcp-download-assets@v1.1.0
              with:
                bucket_source: ${{ secrets.GCP_BUILD_ML_ASSETS2 }}
                run_id: ${{ inputs.run_id }}

            - name: generate metadata info
              id: generate-metadata
              uses: ./.github/actions/gen-metadata-file
              with:
                reportportal_host: ${{ secrets.REPORTPORTAL_HOST }}
                project: compressed-tensors
                gha_url: "https://github.com/neuralmagic/compressed-tensors/actions/runs/${{ inputs.run_id }}"
                wf_category: ${{ inputs.wf_category }}
                gitref: ${{ inputs.gitref }}

            - name: report to reportportal
              uses: neuralmagic/nm-actions/actions/reportportal_submit_execution_results@testmo-to-reportportal
              with:
                droute_username: ${{ secrets.DROUTE_USERNAME }}
                droute_password: ${{ secrets.DROUTE_PASSWORD }}
                droute_url: ${{ secrets.DROUTE_URL}}
                metadata_filepath: ${{ steps.generate-metadata.outputs.metadata_filepath }}
