name: build and test jobs for nightly and release
run-name: ${{ github.actor }} triggered nightly or release on ${{ github.ref }}
on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: '30 0 * * *'  # nightly run

    workflow_call:
        inputs:
            wf_category:
                description: "workflow category, must be 'NIGHTLY' or 'RELEASE' (default: NIGHTLY)"
                type: string
                default: NIGHTLY
            gitref:
                description: "git commit hash or tag name"
                type: string
                default: 'main'

    workflow_dispatch:
        inputs:
            wf_category:
                description: "workflow category, default is NIGHTLY"
                type: choice
                options:
                    - NIGHTLY
                    - RELEASE
                default: NIGHTLY
            gitref:
                description: "git commit hash or tag name"
                type: string
                default: 'main'

jobs:

    BUILD-TEST:
        uses: ./.github/workflows/build-test.yml
        name: ${{ inputs.wf_category || 'NIGHTLY' }}
        with:
            wf_category: ${{ inputs.wf_category || 'NIGHTLY' }}
            gitref: ${{ inputs.gitref || 'main' }}
            test_configs: '[{"python":"3.11.4","label":"ubuntu-latest","timeout":"40","code_coverage":true},
                            {"python":"3.10.12","label":"ubuntu-latest","timeout":"40"},
                            {"python":"3.13","label":"ubuntu-24.04","timeout":"40"},
                            {"python":"3.12.6","label":"ubuntu-22.04","timeout":"40"}]'
        secrets: inherit
