name: build and test jobs for nightly and release
run-name: ${{ github.actor }} triggered nightly on ${{ github.ref }}
on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: '30 0 * * *'  # nightly run

    push:
      branches:
        - auto

    workflow_dispatch:
        inputs:
            wf_category:
                description: "workflow category, default is NIGHTLY"
                type: choice
                options:
                    - NIGHTLY
                    - RELEASE
                default: NIGHTLY
            push_to_pypi:
                description: "only set it to true for RELEASE; when set and tests pass, then '.whl' & '.tar.gz' will be pushed to public pypi"
                type: boolean
                default: false
            gitref:
                description: "git commit hash or tag name" 
                type: string
                default: 'main'

jobs:

    BUILD-TEST:
        uses: ./.github/workflows/build-test.yml
        name: ${{ inputs.wf_category || (github.event.schedule == '30 0 * * *' && 'NIGHTLY') }}
        with:
            #wf_category: ${{ inputs.wf_category || (github.event.schedule == '30 0 * * *' && 'NIGHTLY') }}
            wf_category: ${{ 'RELEASE' || (github.event.schedule == '30 0 * * *' && 'NIGHTLY') }}
            gitref: ${{ inputs.gitref || 'auto' }}
            push_to_pypi: ${{ inputs.push_to_pypi || false }}

            # nightly and weekly tests share the same configs
            test_configs: '[{"python":"3.10.12","label":"ubuntu-20.04","timeout":"60"}]'

        secrets: inherit
